name = "resep-dashboard"
main = "src/index.ts"
compatibility_date = "2024-12-18"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

[triggers]
crons = ["*/5 * * * *"] # Run every 5 minutes

[[routes]]
pattern = "resep.plasodig.my.id"
custom_domain = true

[[d1_databases]]
binding = "DB"
database_name = "resep-db"
database_id = "1eaeaa73-31f6-44d7-82e5-4aec85c7ff50"

[[kv_namespaces]]
binding = "IMAGES"
id = "cad24389814c4ff4856453338c2fde57"

[vars]
AI_POOL_URL = "https://script.google.com/macros/s/AKfycbz-vqpDypJmXQwNSCkyjsa3wTjEnWaWxOURJLLAaZZA99dy8hD_kxxJ963kVuoks0Xi/exec"
RECIPES_SYNC_URL = "https://script.google.com/macros/s/AKfycbyAqk46PLGwKq0U8rs7BlUggpRamWVJeCCiy_WVnApxmIJwCZw-TTWPblmlt05G4Kjm/exec"
