import { html, raw } from "hono/html";

const CSS = `
  :root {
    --bg: #0f1117;
    --surface: #1a1d27;
    --surface2: #22263a;
    --border: #2a2e3f;
    --text: #e8e9ed;
    --text-muted: #8b8fa3;
    --primary: #f97316;
    --font: 'Plus Jakarta Sans', system-ui, -apple-system, sans-serif;
  }
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: var(--font); background: var(--bg); color: var(--text); min-height: 100vh; line-height: 1.6; }
  a { color: var(--primary); text-decoration: none; }
  a:hover { text-decoration: underline; }
  .container { max-width: 800px; margin: 0 auto; padding: 40px 24px; }
  .nav { margin-bottom: 40px; }
  .nav a { display: inline-flex; align-items: center; gap: 6px; padding: 10px 20px; border-radius: 50px; background: var(--surface); border: 1px solid var(--border); font-size: 14px; font-weight: 600; color: var(--text-muted); transition: all .2s; }
  .nav a:hover { border-color: var(--primary); color: var(--text); text-decoration: none; }
  .content { background: var(--surface); padding: 40px; border-radius: 16px; border: 1px solid var(--border); }
  h1 { font-size: 2.5rem; font-weight: 800; margin-bottom: 24px; color: #fff; }
  h2 { font-size: 1.5rem; font-weight: 700; margin-top: 32px; margin-bottom: 16px; color: #fff; }
  p { margin-bottom: 16px; color: var(--text-muted); }
  ul { margin-bottom: 16px; padding-left: 24px; color: var(--text-muted); }
  li { margin-bottom: 8px; }
  footer { text-align: center; padding: 40px 24px; color: var(--text-muted); font-size: 14px; }
  
  @media (max-width: 600px) {
    .content { padding: 24px; }
    h1 { font-size: 2rem; }
  }
`;

export function privacyPolicyPage() {
  return html`<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>Privacy Policy - Resep Nusantara</title>
  <link rel="preconnect" href="https://fonts.googleapis.com" />
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
  <link href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;500;600;700;800&display=swap" rel="stylesheet" />
  <style>${raw(CSS)}</style>
</head>
<body>
  <div class="container">
    <nav class="nav">
      <a href="/">← Back to Home</a>
    </nav>
    <div class="content">
      <h1>Privacy Policy</h1>
      <p><strong>Effective Date:</strong> ${new Date().toISOString().split("T")[0]}</p>
      
      <p>This Privacy Policy applies to the "Resep Nusantara" Android application (Package Name: <code>com.plasodig.resep</code>) and its associated website <code>resep.plasodig.my.id</code> (collectively referred to as the "Service"), operated by Plasodig ("we", "us", or "our").</p>
      
      <h2>1. Information We Collect</h2>
      <p>We may collect information to provide and improve our Service. This includes:</p>
      <ul>
        <li><strong>Usage Data:</strong> We may collect non-personally identifiable information automatically, such as device type, operating system version, app usage statistics, and IP addresses for analytical and rate-limiting purposes.</li>
        <li><strong>Advertising ID:</strong> For our Android application, we use Google AdMob to display advertisements. AdMob may collect and use your device's unique advertising identifier (Advertising ID) and other related information to provide personalized ads.</li>
        <li><strong>Search Queries &amp; Recipe Requests:</strong> When you use the search or "create recipe" features, the content of your search terms is stored permanently to build the recipe catalog. These queries are visible to our admin team for moderation.</li>
        <li><strong>User Reports:</strong> When you flag a recipe via the in-app "Report" button, we store the reason, any free-text detail you submit, and your IP address for moderation purposes.</li>
      </ul>

      <h2>2. AI-Generated Content</h2>
      <p><strong>Important:</strong> All recipes displayed in the Service — including ingredients, cooking steps, and food photographs — are generated by artificial intelligence (Cloudflare Workers AI: Meta Llama for text, Black Forest Labs FLUX for images). We do not guarantee the accuracy, completeness, safety, or authenticity of AI-generated content.</p>
      <ul>
        <li>Always verify ingredients and cooking steps before preparing any dish.</li>
        <li>Recipes are not medical or nutritional advice. Consult a qualified professional for dietary needs.</li>
        <li>If you encounter inaccurate, offensive, or potentially dangerous content, please use the in-app "Report" button so we can remove it.</li>
      </ul>
      <p>The app implements safety filters on both input (query blocklist) and output (health-claim detection) to reduce harmful generation, but no AI safety system is perfect.</p>

      <h2>3. How We Use Information</h2>
      <p>The information we collect is used for:</p>
      <ul>
        <li>Providing, maintaining, and improving the Service.</li>
        <li>Rate-limiting abusive usage (5 generation requests per IP per hour, 20 suggestion queries per IP per hour, 10 reports per IP per hour).</li>
        <li>Moderating user-submitted content via admin dashboard review.</li>
        <li>Serving personalized advertisements through Google AdMob (when applicable).</li>
      </ul>

      <h2>4. Data Retention</h2>
      <ul>
        <li><strong>IP addresses (rate limit):</strong> stored in our edge cache for up to 1 hour, then automatically expire.</li>
        <li><strong>Search queries &amp; recipe requests:</strong> stored permanently in our database as part of the public recipe catalog. Personally identifying information is not associated with queries.</li>
        <li><strong>User reports:</strong> retained for the lifetime of the reported recipe to maintain audit history.</li>
        <li><strong>On-device image cache (mobile):</strong> stored locally on your device (up to 50 MB), cleared automatically via LRU or by clearing app data.</li>
      </ul>

      <h2>5. Third-Party Services</h2>
      <p>Our app uses the following third-party services:</p>
      <ul>
        <li><strong>Cloudflare Workers AI</strong> — for recipe text and image generation. Cloudflare processes your query text during generation. See <a href="https://www.cloudflare.com/privacypolicy/" target="_blank" rel="noopener">Cloudflare Privacy Policy</a>.</li>
        <li><strong>Google AdMob</strong> — when enabled, displays ads and may collect advertising identifiers. See <a href="https://policies.google.com/privacy" target="_blank" rel="noopener">Google Privacy Policy</a>. You can opt out of personalized ads via your Android device's Ad Settings.</li>
      </ul>

      <h2>6. User Rights</h2>
      <ul>
        <li><strong>Report content:</strong> use the in-app flag button to report any recipe. After 3 verified reports, the recipe is auto-unpublished pending admin review.</li>
        <li><strong>Request removal:</strong> if you submitted a query that you want removed from the catalog, contact us via the email below.</li>
        <li><strong>Access/deletion:</strong> since we do not collect personal identifiers, individual-level data deletion is generally not applicable. For specific concerns, contact us.</li>
      </ul>

      <h2>7. Data Security</h2>
      <p>The security of your data is important to us, but remember that no method of transmission over the Internet or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your personal information, we cannot guarantee its absolute security.</p>

      <h2>8. Children's Privacy</h2>
      <p>Our Service does not address anyone under the age of 13 ("Children"). We do not knowingly collect personally identifiable information from anyone under the age of 13. If you are a parent or guardian and you are aware that your Child has provided us with Personal Data, please contact us.</p>

      <h2>9. Changes to This Privacy Policy</h2>
      <p>We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.</p>

      <h2>10. Contact Us</h2>
      <p>If you have any questions about this Privacy Policy, please contact us:</p>
      <ul>
        <li>Email: <a href="mailto:plasodig@gmail.com">plasodig@gmail.com</a></li>
        <li>Contact Page: <a href="/contacts">resep.plasodig.my.id/contacts</a></li>
        <li>Terms of Use: <a href="/terms">resep.plasodig.my.id/terms</a></li>
      </ul>
    </div>
  </div>
  <footer>
    <p>&copy; ${new Date().getFullYear()} Resep Nusantara — <a href="https://resep.plasodig.my.id">resep.plasodig.my.id</a></p>
  </footer>
</body>
</html>`;
}

export function termsOfUsePage() {
  return html`<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>Terms of Use - Resep Nusantara</title>
  <link rel="preconnect" href="https://fonts.googleapis.com" />
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
  <link href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;500;600;700;800&display=swap" rel="stylesheet" />
  <style>${raw(CSS)}</style>
</head>
<body>
  <div class="container">
    <nav class="nav">
      <a href="/">← Back to Home</a>
    </nav>
    <div class="content">
      <h1>Terms of Use</h1>
      <p><strong>Effective Date:</strong> ${new Date().toISOString().split("T")[0]}</p>

      <p>By using the "Resep Nusantara" application (<code>com.plasodig.resep</code>) or the website <code>resep.plasodig.my.id</code> ("Service"), you agree to these Terms of Use. If you do not agree, do not use the Service.</p>

      <h2>1. Nature of Content</h2>
      <p>All recipes in the Service are <strong>generated by artificial intelligence</strong>. The Service, its operators, and the AI providers make no warranty of any kind regarding the accuracy, authenticity, safety, or completeness of any recipe. Ingredients, quantities, cooking times, and techniques may be incorrect.</p>

      <h2>2. Not Medical or Nutritional Advice</h2>
      <p>Content in the Service is not medical, nutritional, or dietary advice. Do not rely on AI-generated recipes for medical decisions. Consult a qualified professional for allergies, dietary restrictions, or health conditions.</p>

      <h2>3. Assumption of Risk</h2>
      <p>You prepare and consume recipes at your own risk. Always verify ingredients are safe, fresh, non-allergenic, and sourced from trusted suppliers. Check for food safety warnings (undercooked meats, raw eggs, allergens, choking hazards for children) before cooking.</p>

      <h2>4. Acceptable Use</h2>
      <p>You may not:</p>
      <ul>
        <li>Submit queries or requests for non-food content (weapons, drugs, adult content, medical claims, hate speech, etc.).</li>
        <li>Attempt to bypass safety filters or rate limits.</li>
        <li>Use the Service to generate content intended to harm others.</li>
        <li>Reverse-engineer, scrape, or redistribute the Service without permission.</li>
      </ul>
      <p>We reserve the right to block access and report abusive queries.</p>

      <h2>5. Reporting Objectionable Content</h2>
      <p>If you encounter a recipe that is inaccurate, offensive, or potentially dangerous, please use the in-app Report button. Reports are reviewed by our admin team; recipes that receive 3 or more reports are automatically unpublished pending review.</p>

      <h2>6. Limitation of Liability</h2>
      <p>TO THE MAXIMUM EXTENT PERMITTED BY LAW, WE SHALL NOT BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING BUT NOT LIMITED TO FOOD POISONING, ALLERGIC REACTIONS, PROPERTY DAMAGE, LOST PROFITS, OR LOSS OF DATA, ARISING FROM USE OF THE SERVICE OR RELIANCE ON ANY CONTENT THEREIN.</p>

      <h2>7. Intellectual Property</h2>
      <p>Recipe text is generated by Meta Llama models (Llama 3 Community License). Images are generated by Black Forest Labs FLUX.1-schnell (Apache 2.0). App code and UI copyright belong to Plasodig. You may use recipes generated by the Service for personal, non-commercial cooking.</p>

      <h2>8. Changes</h2>
      <p>We may update these Terms at any time. Continued use of the Service constitutes acceptance of the updated Terms.</p>

      <h2>9. Contact</h2>
      <p>Questions? <a href="mailto:plasodig@gmail.com">plasodig@gmail.com</a> | <a href="/privacy-policy">Privacy Policy</a></p>
    </div>
  </div>
  <footer>
    <p>&copy; ${new Date().getFullYear()} Resep Nusantara — <a href="https://resep.plasodig.my.id">resep.plasodig.my.id</a></p>
  </footer>
</body>
</html>`;
}

export function contactPage() {
  return html`<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>Contact Us - Resep Nusantara</title>
  <link rel="preconnect" href="https://fonts.googleapis.com" />
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
  <link href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;500;600;700;800&display=swap" rel="stylesheet" />
  <style>${raw(CSS)}</style>
  <style>
    .contact-card { display: flex; align-items: center; gap: 16px; padding: 24px; background: var(--surface2); border-radius: 12px; margin-top: 24px; border: 1px solid var(--border); }
    .contact-icon { font-size: 32px; background: rgba(249,115,22,0.1); width: 64px; height: 64px; display: flex; align-items: center; justify-content: center; border-radius: 50%; color: var(--primary); }
    .contact-info h3 { margin-bottom: 4px; color: #fff; font-size: 18px; }
    .contact-info p { margin: 0; }
  </style>
</head>
<body>
  <div class="container">
    <nav class="nav">
      <a href="/">← Back to Home</a>
    </nav>
    <div class="content">
      <h1>Contact Us</h1>
      <p>If you have any questions about the <strong>Resep Nusantara</strong> Android app or our website, please feel free to reach out to us. We will get back to you as soon as possible.</p>
      
      <div class="contact-card">
        <div class="contact-icon">✉️</div>
        <div class="contact-info">
          <h3>Email Us</h3>
          <p><a href="mailto:plasodig@gmail.com">plasodig@gmail.com</a></p>
        </div>
      </div>
      
      <div class="contact-card">
        <div class="contact-icon">🌐</div>
        <div class="contact-info">
          <h3>Website</h3>
          <p><a href="https://resep.plasodig.my.id">resep.plasodig.my.id</a></p>
        </div>
      </div>
      
      <div style="margin-top: 40px; padding-top: 24px; border-top: 1px solid var(--border);">
        <p><strong>App Package Name:</strong> <code>com.plasodig.resep</code></p>
        <p>Before emailing for support, please ensure you've read our <a href="/privacy-policy">Privacy Policy</a>.</p>
      </div>
    </div>
  </div>
  <footer>
    <p>&copy; ${new Date().getFullYear()} Resep Nusantara — <a href="https://resep.plasodig.my.id">resep.plasodig.my.id</a></p>
  </footer>
</body>
</html>`;
}
